; 这里放 custom/rules.ini 对应的策略组。
; 注意：custom_proxy_group 的名字必须和 ruleset= 后面的应用名一致。

; 示例：对应 custom/rules.ini 里的 Discord
; custom_proxy_group= Discord`select`[]🇭🇰 HK`[]🇹🇼 TW`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🧊 冷门节点`[]🌐 Default

; 示例：对应 MySite
custom_proxy_group= 走国内`select`[]🇭🇰 HK`[]🇹🇼 TW`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🧊 冷门节点`[]DIRECT`[]🌐 Default
custom_proxy_group= 走国外`select`[]🇭🇰 HK`[]🇹🇼 TW`[]🇯🇵 JP`[]🇸🇬 SG`[]🇺🇸 US`[]🧊 冷门节点`[]DIRECT`[]🌐 Default
; 你的自定义策略组
custom_proxy_group=访问新加坡`select`[]🇸🇬 SG`[]🌐 Default`[]🇭🇰 HK`[]🇯🇵 JP`[]🇺🇸 US`[]DIRECT
