; 这里放你自己新增的分流规则。
; 写法参考：
; ruleset= 应用名,[]GEOSITE,规则名
; ruleset= 应用名,clash-domain:https://example.com/domain.yaml,86400
; ruleset= 应用名,clash-classic:https://example.com/classical.yaml,86400

; 示例：如果以后想单独管理 Discord，可以取消下面这一行注释
; ruleset= Discord,[]GEOSITE,discord

; 示例：如果某个网站没有 GEOSITE，可自己维护一个 yaml
; ruleset= MySite,clash-domain:https://raw.githubusercontent.com/Bloomberg-zhong/openclash-rules/main/rules/mysite.yaml,86400
